[package]
name = "day04"
version = "0.1.0"
authors = ["Joel Smith <Hikash@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
other-md5 = {version = "0.8.0", package = "md-5"}
hex = "0.3.1"
md5 = "0.6.1"